check connection to registry
MHI-EMEA-DS/yais pull request #16
Opened 2023-10-24 07:36 UTC by AndreySinenok

GCCP-7816

2023-10-24 18:25 UTC, ivanbenko requested changes

2023-10-24 18:25 UTC, ivanbenko commented on chartman.sh
> +if [ "$runDockerArgs" == "" ]; then
better to check `$requestedVersion` since its absence causes the problem

2023-10-24 18:25 UTC, ivanbenko commented on chartman.sh
> +  echo "Checking connection to docker registry"
the idea was to capture output of underlying command and output it here, it should contain enough diagnostic info about the problem

2023-10-24 18:25 UTC, ivanbenko commented on chartman.sh
> +  echo "Checking connection to docker registry"
take a look at line 57

2023-10-27 17:54 UTC, ivanbenko commented on chartman.sh
> +  echo "Checking connection to docker registry"
@AndreySinenok this is not done

2023-10-30 16:22 UTC, alekseysavostin commented on chartman.sh
> +  ping -c 1 docker-registry.ds.mhie.com;
take registry from variable

2023-11-15 13:24 UTC, merged