custom chartman home directory
MHI-EMEA-DS/yais pull request #9
Opened 2023-09-13 10:07 UTC by dzmitryPadhrusha

#GCCP-7667

2023-09-15 07:12 UTC, ivanbenko requested changes

2023-09-15 07:12 UTC, ivanbenko commented on yais.sh
> +    -v "${ARG_CHARTMAN_HOME}/.chartman":"/app/data/.chartman" \
it's expected that `ARG_CHARTMAN_HOME` include `.chartman` as well,
so default value is `${HOME}/.chartman` and here it should be mounted as `${ARG_CHARTMAN_HOME}":"/app/data/.chartman`

2023-09-15 20:24 UTC, dzmitryPadhrusha commented on yais.sh
> +    -v "${ARG_CHARTMAN_HOME}/.chartman":"/app/data/.chartman" \
fixed

2023-09-19 06:47 UTC, ivanbenko approved these changes

2023-09-19 06:47 UTC, merged